#!/bin/bash
sudo cp -rf gooey_shell gooeyde_appmenu gooeyde_start gooeyde_desktop  roboto.ttf /usr/local/bin/
sudo cp assets/ /usr/share/icons/ -r

sudo cp gooeyde.desktop /usr/share/xsessions/gooeyde.desktop
sudo chmod 644 /usr/share/xsessions/gooeyde.desktop
sudo chmod +x /usr/local/bin/gooey_shell
sudo chmod +x /usr/local/bin/gooeyde_appmenu
sudo chmod +x /usr/local/bin/gooeyde_desktop
sudo chmod +x /usr/local/bin/gooeyde_start
